## 2020. 02. 24.

### 코틀린 - 코루틴 취소와 타임아웃(3)

#### 취소 불가능한 블럭 실행

이전 예제의 `finally` 블럭에서 지연 함수를 사용하면 [`CancellationException`][kt-cancellation-exception]이 발생한다. 이 코드를 실행하는 코루틴이 취소됐기 때문이다. 보통 잘 만들어진 (파일, 작업 혹은 통신 채널을 닫는 것과 같은)닫기 연산은 넌블로킹으로 실행되고 지연 함수와는 관련 없기 때문에 문제가 되지 않는다. 드물긴 하지만 취소된 코루틴에서 지연이 필요한 경우, 아래 예시와 같이 [`withContext`][kt-with-context] 함수와 [`NonCancellable`][kt-non-cancellable] 컨텍스트를 사용해 해당 코드를 `withContext(NonCancellable) { ... }`로 래핑할 수 있다:

```kotlin
val job = launch {
    try {
        repeat(1000) { i ->
            println("job: I'm sleeping $i ...")
            delay(500L)
        }
    } finally {
        withContext(NonCancellable) {
            println("job: I'm running finally")
            delay(1000L)
            println("job: And I've just delayed for 1 sec because I'm non-cancellable")
        }
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```



[kt-cancellation-exception]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-cancellation-exception/index.html
[kt-with-context]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/with-context.htmlhttps://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/with-context.html