## 2020. 04. 09.

### 코틀린 - 예외 처리와 관리(2)

#### `CoroutineExceptionHandler`

만일 모든 예외를 콘솔에 출력하고 싶지 않은 경우에는 어떻게 해야 할까? [`CoroutineExceptionHandler`][kt-coroutine-coroutine-exception-handler] 컨텍스트 요소는 코루틴에서 커스텀 로깅이나 예외 처리가 필요한 곳에서 일반적인 `catch` 블럭으로 사용된다. 이는 [`Thread.uncaughtExceptionHandler`][java-thread-uncaught-exception-handler]를 사용하는 것과 비슷하다.

JVM에서는 [`ServiceLoader`][java-service-loader]를 통해 [`CoroutineExceptionHandler`][kt-coroutine-coroutine-exception-handler]를 등록함으로써 모든 코루틴에 대한 전역 예외 핸들러를 재정의할 수 있다. 전역 예외 핸들러는 추가적인 핸들러가 등록되지 않았을 때 사용되는 [`Thread.defaultUncaughtExceptionHandler`][java-thread-default-uncaught-exception-handler]와 비슷하다. 안드로이드에서는 `uncaughtExceptionPreHandler`가 전역 코루틴 예외 핸들러로 설정된다.

[`CoroutineExceptionHandler`][kt-coroutine-coroutine-exception-handler]는 사용자가 처리할 것으로 예상되지 않는 예외들에 대해서만 호출된다. 따라서 [`async`][kt-coroutine-async] 빌더에 이를 등록하거나 하는 일은 아무런 효과가 없다.

```kotlin
val handler = CoroutineExceptionHandler { _, exception -> 
    println("Caught $exception") 
}
val job = GlobalScope.launch(handler) {
    throw AssertionError()
}
val deferred = GlobalScope.async(handler) {
    throw ArithmeticException() // Nothing will be printed, relying on user to call deferred.await()
}
joinAll(job, deferred)
```

이 코드는 다음과 같이 출력된다:

```
Caught java.lang.AssertionError
```



[kt-coroutine-coroutine-exception-handler]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-exception-handler/index.html
[java-thread-uncaught-exception-handler]: https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#setUncaughtExceptionHandler(java.lang.Thread.UncaughtExceptionHandler)
[java-service-loader]: https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html
[java-thread-default-uncaught-exception-handler]: https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#setDefaultUncaughtExceptionHandler(java.lang.Thread.UncaughtExceptionHandler)
[kt-coroutine-async]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html